name: Deploy to LocalStack + PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - name: Check commit message for [deploy]
        id: check
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -q "\[deploy\]"; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Detectado [deploy] en el mensaje de commit"
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
            echo "No se detectó [deploy], saltando despliegue"
          fi

  deploy:
    needs: check-deploy
    if: needs.check-deploy.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        run: |
          pip install awscli

      - name: Setup PostgreSQL Schema
        run: |
          echo "=== Configurando PostgreSQL ==="

          # Instalar cliente psql
          apt-get update && apt-get install -y postgresql-client

          # Esperar a que PostgreSQL esté listo
          until PGPASSWORD=secretpass123 psql -h postgres -U admin -d myapp -c '\q' 2>/dev/null; do
            echo "Esperando PostgreSQL..."
            sleep 2
          done

          # Crear schema de la aplicación
          PGPASSWORD=secretpass123 psql -h postgres -U admin -d myapp << 'EOF'
          -- Tabla de usuarios
          CREATE TABLE IF NOT EXISTS users (
              id SERIAL PRIMARY KEY,
              email VARCHAR(255) UNIQUE NOT NULL,
              name VARCHAR(255),
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );

          -- Tabla de configuración
          CREATE TABLE IF NOT EXISTS app_config (
              key VARCHAR(255) PRIMARY KEY,
              value TEXT,
              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );

          -- Insertar configuración inicial
          INSERT INTO app_config (key, value) VALUES ('version', '1.0.0')
          ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = CURRENT_TIMESTAMP;

          SELECT 'Schema PostgreSQL configurado correctamente' as status;
          EOF

          echo "=== Verificando tablas PostgreSQL ==="
          PGPASSWORD=secretpass123 psql -h postgres -U admin -d myapp -c '\dt'

      - name: Deploy DynamoDB Tables to LocalStack
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "=== Creando tabla DynamoDB para sesiones ==="
          aws --endpoint-url=http://localstack:4566 dynamodb create-table \
            --table-name sessions \
            --attribute-definitions \
              AttributeName=sessionId,AttributeType=S \
            --key-schema \
              AttributeName=sessionId,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            2>/dev/null || echo "Tabla sessions ya existe"

          echo "=== Creando tabla DynamoDB para cache ==="
          aws --endpoint-url=http://localstack:4566 dynamodb create-table \
            --table-name cache \
            --attribute-definitions \
              AttributeName=cacheKey,AttributeType=S \
            --key-schema \
              AttributeName=cacheKey,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            2>/dev/null || echo "Tabla cache ya existe"

          echo "=== Verificando tablas DynamoDB ==="
          aws --endpoint-url=http://localstack:4566 dynamodb list-tables

      - name: Deploy EC2 Instance to LocalStack
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "=== Creando instancia EC2 ==="
          INSTANCE_ID=$(aws --endpoint-url=http://localstack:4566 ec2 run-instances \
            --image-id ami-0123456789abcdef0 \
            --instance-type t2.micro \
            --count 1 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=myapp-server},{Key=Environment,Value=dev}]' \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "Instancia creada: $INSTANCE_ID"

          echo "=== Verificando EC2 ==="
          aws --endpoint-url=http://localstack:4566 ec2 describe-instances \
            --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0]]' \
            --output table

      - name: Deployment Summary
        run: |
          echo ""
          echo "=========================================="
          echo "        DESPLIEGUE COMPLETADO"
          echo "=========================================="
          echo ""
          echo "PostgreSQL (datos relacionales):"
          echo "  Host: localhost:5432"
          echo "  DB:   myapp"
          echo "  User: admin"
          echo "  Tablas: users, app_config"
          echo ""
          echo "DynamoDB en LocalStack (cache/sesiones):"
          echo "  Endpoint: localhost:4566"
          echo "  Tablas: sessions, cache"
          echo ""
          echo "EC2 en LocalStack:"
          echo "  Instance: myapp-server"
          echo "=========================================="
